### ISSUE TITLE
G200S integration problem

### ISSUE THREAD

**Issue by talex79** [mavrikkk/ha_kettler#59]
Никак не получается справиться с подключением чайника G200S. HA развернут в конфигурации Supervised на RPI 4b.
Blutooth встроенный в RPI. Чайник в двух метрах от RPI.

Ваш компонент установлен через HACS. При добавлении интеграции чайник и его MAC отображается в окне настройки конфигурации. При этом после нажатия кнопки подтвердить интерфейс залипает. Дальше ничего не происходит. Если отменить создание, то получаю пустую интеграцию

Подскажите, пожалуйста, куда смотреть дальше?

В логе HA вижу такие ошибки
```
2021-01-09 18:31:45 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry e9:9d:16:2c:30:1e for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 321, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 72, in async_unload_entry
return await hass.data[DOMAIN].async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-01-09 18:31:45 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry e9:9d:16:2c:30:1e for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 321, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 270, in async_unload_entry
return await hass.data[DOMAIN].async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-01-09 18:31:45 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry e9:9d:16:2c:30:1e for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 321, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 78, in async_unload_entry
return await hass.data[DOMAIN].async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!


```

**Comment by mavrikkk** [comment]
по шагам делаете?
1. поиск устройства.
2. выбор из списка, заполнение пароля
3. перевод чайника в режим сопряжения и только потом
4. нажатие далее для подключения.

Выше ошибки неинформативные, они лишь говорят о том, что не получается удалить устройство, так как оно не создано...это уже к последующим вашим попыткам, а не к попытке подключения

**Comment by mavrikkk** [comment]
срок давности
