### ISSUE TITLE
LOGGER.error(str(hass.data[DOMAIN]))

### ISSUE THREAD

**Issue by pavoroby** [mavrikkk/ha_kettler#65]
После обновления компонента и повторной привязки устройства возникает ошибка
```
Error setting up entry f4:18:d8:08:2d:a5 for ready4sky
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ready4sky/__init__.py", line 68, in async_setup_entry
    _LOGGER.error(str(hass.data[DOMAIN]))
KeyError: 'ready4sky'
```

Сущности не создаются.

Так же предупреждение
```
You are using a custom integration for ready4sky which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Comment by pavoroby** [comment]
Что интересно, параметр "использовать подсветку", задаваемый в первичной настройке, работает. Устройство живет с подсветкой или без нее, в зависимости от выбранного режима.

**Comment by pavoroby** [comment]
После обновления с исправлением https://github.com/mavrikkk/ha_kettler/commit/4c8e1a92f05d87d1cf9502fa48e1c12d30b35c08 проблема ушла.
