### ISSUE TITLE
RK-G 201 не появляется устройство после подключения

### ISSUE THREAD

**Issue by Machaeon** [mavrikkk/ha_kettler#67]
HA установлен в докере на NUC n3050, Ubuntu 16.04.
Компонент установлен через HACS.
После выбора устройства в окне конфигурации и сопряжения, интеграция сообщает об успехе, MAC устройства отображается в карточке интеграции, но списка устройств и объектов в карточке не появляется.

**Comment by ARNik** [comment]
Была такая же ерунда с другим чайником. 
Несколько раз переподключил и все сработало.

Попробуй подключить  по следующему варианту.
1 Полная перезагрузка (не только ядро)
2 Включаем интеграцию
3 Ищем чайник (на самом чайнике ничего не жмем)
4 Когда чайник найдется, заполняем карточку вместе с паролем и т.д.
5 Жмем далее пока не увидим предупреждение что надо включить режим спаривания
6 Переключаем чайник в режим спаривания и тут же нажимаем submit или что-то там.

**Comment by Machaeon** [comment]
> 3 Ищем чайник (на самом чайнике ничего не жмем)

А как ищем? После установки интеграции у меня появляется карточка со списком устройств, в котором чайник уже указан.

**Comment by ARNik** [comment]
Подожди немного и он появится. 
Либо пни его через приложение на телефоне.

**Comment by Machaeon** [comment]
А если я его к приложению в телефоне прикручу, он от HA не отвалится?

**Comment by Machaeon** [comment]
Ха, в приложении пишет: Девайс отклонил запрос на пэйринг.

**Comment by Mac-lucky** [comment]
It's not working for me either. I tried everything for about 3 hours

**Comment by mavrikkk** [comment]
> MAC устройства отображается в карточке интеграции, но списка устройств и объектов в карточке не появляется

как отображается устройство в списке найденных? либо скрин либо скопируйте

**Comment by mavrikkk** [comment]
> It's not working for me either. I tried everything for about 3 hours

what exactly did you do?
can you see your device in this (https://user-images.githubusercontent.com/9576189/78805578-3fdca180-79ca-11ea-9dda-5710c7f46f66.png) list?

**Comment by Machaeon** [comment]
> как отображается устройство в списке найденных? либо скрин либо скопируйте
[https://postimg.cc/gallery/fV3nRH3](url)

**Comment by mavrikkk** [comment]
делаете строго по инструкции?
что в логах после подключения?

**Comment by Machaeon** [comment]
Делаю по инструкции. В логах ошибка:
 Connect to ef:ee:... through device hci0 failed

**Comment by mavrikkk** [comment]
вылет при попытке коннекта.
причем не просто неудачная попытка, а именно вылет из функции. Если разбираетесь в коде, то могу подсказать, что исправить, чтобы увидеть истинную ошибку.

**Comment by Machaeon** [comment]
С питоном знаком слабо, но попробовать могу, подскажите, что сделать.

**Comment by Mac-lucky** [comment]
> > It's not working for me either. I tried everything for about 3 hours
> 
> what exactly did you do?
> can you see your device in this (https://user-images.githubusercontent.com/9576189/78805578-3fdca180-79ca-11ea-9dda-5710c7f46f66.png) list? If you can, copy here the name of your device

Yes, I can see my kettler in the first config and then I just get a blank card with no entity and no device, just a blank card with mac adress of my kettler. 

I have the RK-G200S, but from what I see a lot of people have the same problem.

**Comment by mavrikkk** [comment]
> С питоном знаком слабо, но попробовать могу, подскажите, что сделать.

Откройте файл __init__.py любым текстовым редактором. Строчки 68-75 содержат конструкцию try except. Надо закомментировать строчки 68, 73,74,75. А строчки 69,70,71,72 сдвинуть на 4 пробела влево. 
Сохранить и попробовать подключить чайник заново. Ошибки с логов - сюда по результату.

**Comment by mavrikkk** [comment]
> just a blank card with mac adress of my kettler.

What do you see in your LOGs? Paste here.



> I have the RK-G200S

this model is 100% supported. I had this model several years ago.

**Comment by Machaeon** [comment]
Вот лог:
`Logger: homeassistant.config_entries
Source: custom_components/ready4sky/__init__.py:709
First occurred: 14:53:21 (1 occurrences)
Last logged: 14:53:21

Error setting up entry ef:ee:... for ready4sky
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ready4sky/__init__.py", line 69, in async_setup_entry
    await kettler.async_firstConnect()
  File "/config/custom_components/ready4sky/__init__.py", line 699, in async_firstConnect
    await self.hass.async_add_executor_job(self.firstConnect)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ready4sky/__init__.py", line 671, in firstConnect
    self.findType()
  File "/config/custom_components/ready4sky/__init__.py", line 709, in findType
    ble_devices = {device.addr:str(device.getValueText(9)) for device in scanner.scan(3.0)}
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 800, in start
    self._mgmtCmd(self._cmd())
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scan'
`

**Comment by mavrikkk** [comment]
не получается скан запустить. Вы разрешили работу блютуса без рут прав? где то в закрытых issues поищите.
Что то вроде этого:

sudo setcap 'cap_net_raw,cap_net_admin+eip' bluepy-helper

sudo setcap 'cap_net_raw,cap_net_admin+eip' bluepy

sudo hciconfig hci0 down && sudo hciconfig hci0 up

Возможно еще что то.

В HassOS и в Hassio это введено автоматом, так как минимум 1 интеграция встроенная использует данную библиотеку. Во всех остальных случаях (manual, venv, docker и тд) нужно это делать вручную

**Comment by Machaeon** [comment]
Спасибо! Помогли рекомендации отсюда:
https://www.home-assistant.io/integrations/bluetooth_le_tracker/

**Comment by diestake** [comment]
У меня чайник RK-200S. Та же проблема: карточка с маком устройства, сущности не создаются.
Использую Hass.io на виртуальной машине VMware Workstation 15 
Операционная система хоста | Home Assistant OS 5.12
Версия | core-2021.3.4
Версия Supervisor | supervisor-2021.03.6
Версия Docker | 19.03.13

В логах:
Logger: homeassistant.config_entries
Source: custom_components/ready4sky/__init__.py:709
First occurred: 0:07:23 (1 occurrences)
Last logged: 0:07:23

Error setting up entry cf:0a:d8:a9:a1:91 for ready4sky
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ready4sky/__init__.py", line 69, in async_setup_entry
    await kettler.async_firstConnect()
  File "/config/custom_components/ready4sky/__init__.py", line 699, in async_firstConnect
    await self.hass.async_add_executor_job(self.firstConnect)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ready4sky/__init__.py", line 671, in firstConnect
    self.findType()
  File "/config/custom_components/ready4sky/__init__.py", line 709, in findType
    ble_devices = {device.addr:str(device.getValueText(9)) for device in scanner.scan(3.0)}
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 12, error: Not Supported)

Помогите, пожалуйста, победить проблему

**Comment by diestake** [comment]
Действовал строго по инструкции, пробовал раз 15 - не взлетало.
В итоге получилось так: 
Заполнил карточку, в последнем пункте про подсветку выбрал 'false'
Нажал продолжить и сразу ещё раз продолжить и только потом активировал режим сопряжения на чайнике (прошло коло 5 секунд).

**Comment by tayanov** [comment]
В системе два hci. при чем первый 2.0. Отключить его не выходит, и при сканировании я вижу датчик температуры, а чайник который гораздо болиже не вижу. грешу что сканирует hci0. Но чайник видится только через hci1. Что можно сделать?

**Comment by mavrikkk** [comment]
> В системе два hci. при чем первый 2.0. Отключить его не выходит, и при сканировании я вижу датчик температуры, а чайник который гораздо болиже не вижу. грешу что сканирует hci0. Но чайник видится только через hci1. Что можно сделать?

В своем модуле сделал привязку устройства. При первоначальной настройке выбираете правильный hci и чайник будет привязан к этому свистку и общаться только через него. 

Как другие ваши устройства общаются с другим свистком я не знаю. Возможно другие модули пытаются залезть на свисток, к которому привязан чайник?

У меня был опыт работы с двумя блютус устройствами, но немного в другом ключе. Один я использовал  для чайника, а второй - для передачи звука по блютус. Оба работали одновременно и не мешая друг другу.

**Comment by tayanov** [comment]
Спасибо за разработку и все же почти год назад тестировал интеграцию со своим 216 чайником, тогда все работало, только блютус был далеко. На днях сервер переехал очень близко к чайнику. Но я получаю ошибку five attempts of firstConnect failed
Интеграция висит красным, мак виден, сущности нет. Что могло поменяться в версиях?
