### ISSUE TITLE
Проблема активации и удаления устройства после перехода на 2022.8.4

### ISSUE THREAD

**Issue by vsimanin** [mavrikkk/ha_kettler#97]
Проблема началась с перехода на 2022.08.*
Долгое время интеграция была деактивирована. Решил удалить ее, но она не удаляется... Запустить ее тоже не получается, в обоих случаях ошибка.

**При попытке удалить устройство:**
Logger: aiohttp.server
Source: custom_components/ready4sky/[init.py:6](https://init.py:6/)
Integration: ready4sky (documentation)
First occurred: 22:41:26 (4 occurrences)
Last logged: 22:43:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_[protocol.py](https://protocol.py/)", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_[app.py](https://app.py/)", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_[middlewares.py](https://middlewares.py/)", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_[filter.py](https://filter.py/)", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/[forwarded.py](https://forwarded.py/)", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_[context.py](https://context.py/)", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/[ban.py](https://ban.py/)", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/[auth.py](https://auth.py/)", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/[view.py](https://view.py/)", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_[entries.py](https://entries.py/)", line 84, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_[entries.py](https://entries.py/)", line 911, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_[entries.py](https://entries.py/)", line 532, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/[loader.py](https://loader.py/)", line 638, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/[init.py](https://init.py/)", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ready4sky/[init.py](https://init.py/)", line 6, in <module>
    from bluepy import btle
ModuleNotFoundError: No module named 'bluepy'

**При попытке включить интеграцию из статуса деактивировано:**
Logger: homeassistant.util.package
Source: util/[package.py:98](https://package.py:98/)
First occurred: 22:51:28 (1 occurrences)
Last logged: 22:51:28

Unable to install package bluepy: error: subprocess-exited-with-error × python [setup.py](https://setup.py/) bdist_wheel did not run successfully. │ exit code: 1 ╰─> [8 lines of output] [/usr](tg://bot_command?command=usr)[/local](tg://bot_command?command=local)[/lib](tg://bot_command?command=lib)[/python3](tg://bot_command?command=python3).10/site-packages/setuptools/[dist.py:772](https://dist.py:772/): UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running bdist_wheel running build running build_py Working dir is [/tmp](tg://bot_command?command=tmp)[/pip](tg://bot_command?command=pip)-install-vvdtihem[/bluepy](tg://bot_command?command=bluepy)_0859265be0374d05bfb7947cafec4353 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for bluepy error: subprocess-exited-with-error × Running [setup.py](https://setup.py/) install for bluepy did not run successfully. │ exit code: 1 ╰─> [10 lines of output] [/usr](tg://bot_command?command=usr)[/local](tg://bot_command?command=local)[/lib](tg://bot_command?command=lib)[/python3](tg://bot_command?command=python3).10/site-packages/setuptools/[dist.py:772](https://dist.py:772/): UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install [/usr](tg://bot_command?command=usr)[/local](tg://bot_command?command=local)[/lib](tg://bot_command?command=lib)[/python3](tg://bot_command?command=python3).10/site-packages/setuptools/command/[install.py:34](https://install.py:34/): SetuptoolsDeprecationWarning: [setup.py](https://setup.py/) install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py Working dir is [/tmp](tg://bot_command?command=tmp)[/pip](tg://bot_command?command=pip)-install-vvdtihem[/bluepy](tg://bot_command?command=bluepy)_0859265be0374d05bfb7947cafec4353 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> bluepy note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.

Если удалить компонент из HACS, не удаляя устройство, то выходит третий вид ошибки + не уходят устройства. 

Помогите, пожалуйста вычистить...

**Comment by vsimanin** [comment]
Проблему решил путем удаления этого проекта из HACS и установкой https://github.com/XNicON/hassio-r4s
Далее ребут НА и устройства можно удалять. На заметку, если кто-то еще столкнется с проблемой.
